# Generated by Django 5.0.7 on 2025-10-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='accounts_pa_user_id_e5b29b_idx',
            old_name='accounts_pas_user_id_5f68e4_idx',
        ),
    ]
