# Generated by Django 5.0.7 on 2025-10-25 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_logintwofactortoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='logintwofactortoken',
            new_name='accounts_lo_user_id_918480_idx',
            old_name='accounts_login_token_idx',
        ),
    ]
