# Generated by Django 5.0.7 on 2025-10-17 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrailCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Trail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("moderate", "Moderate"),
                            ("hard", "Hard"),
                        ],
                        default="moderate",
                        max_length=16,
                    ),
                ),
                ("distance_km", models.FloatField(default=0)),
                ("duration_mins", models.IntegerField(default=0)),
                ("elev_gain_m", models.IntegerField(default=0)),
                (
                    "latitude",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90.0),
                            django.core.validators.MaxValueValidator(90.0),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180.0),
                            django.core.validators.MaxValueValidator(180.0),
                        ],
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=80)),
                ("country", models.CharField(blank=True, max_length=80)),
                (
                    "approval_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="approved",
                        max_length=16,
                    ),
                ),
                ("rating_avg", models.FloatField(default=0)),
                ("rating_count", models.IntegerField(default=0)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="trails", to="trails.trailcategory"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
