# Generated by Django 5.0.7 on 2025-10-24 03:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_trail_route_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='route_geometry',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, help_text='PostGIS geometry representing the trail route for spatial queries.', null=True, srid=4326),
        ),
    ]
