# Generated by Django 5.0.7 on 2025-10-24 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_trail_comment_count_trail_rating_count_and_more'),
        ('trails', '0004_add_route_geometry_index'),
    ]

    operations = [
    ]
