# Generated by Django 5.0.7 on 2025-10-24 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0006_trailcompletion'),
        ('trails', '0006_trailsubmission'),
    ]

    operations = [
    ]
