# Generated by Django 5.0.7 on 2025-10-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0008_trail_submitted_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='approval_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16),
        ),
        migrations.DeleteModel(
            name='TrailSubmission',
        ),
    ]
