# Generated by Django 5.0.7 on 2025-10-25 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0010_trail_save_count_bookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trail_photos/')),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='trails.trail')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trail_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='trailphoto',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('trail',), name='one_primary_photo_per_trail'),
        ),
    ]
